# Page settings
baseurl = "http://resume.johnboyd.io"
languageCode = "en-us"
title = "John Boyd Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"
publishDir = "docs"

[params]

# Meta
    description = "Resume/CV for John Boyd"
    author = "John Boyd"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "John Boyd"
        tagline = "Electrical Engineer"
        avatar = "headshot.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: johnboydiv@gmail.com"
        title = "johnboydiv@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+18177077211"
        title = "+1 (817) 707-7211"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "http://blog.johnboyd.io"
        title = "Project Portfolio"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/john-boyd-iv"
        title = "LinkedIn Profile"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/phreaknik"
        title = "GitHub Profile"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc Electrical Engineering\n\nAnalog & Mixed Signal VLSI\n\nGPA: 3.5"
        college = "Texas A&M University"
        dates = "2014 - 2015"

        [[params.education.list]]
        degree = "BSc Electrical Engineering\n\nGPA: 3.34 | Dean's List"
        college = "Texas A&M University"
        dates = "2009 - 2014"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Spanish"
        level = "Conversational"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Hardware Hacking"

        [[params.interests.list]]
        interest = "Rock Climbing"

        [[params.interests.list]]
        interest = "Snowboarding"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """I am an electrical engineer with a passion for all things electronic. Since childhood, I
        have spent most of my time either tearing apart old gadgets or hacking together new creations of my own.
        This passion for tech exploration and innovation has had a strong impact on my career path.\n\nI studied
        electrical engineering at Texas A&M, where I graduated with a Masters Degree in electrical engineering. In
        school I focused on analog and mixed signal VLSI design, and ultimately spent a few years doing semiconductor
        design. Throughout my time in school and at work in the semiconductor industry, I continued to work on
        personal projects spanning a wide array of technologies, ranging from embedded system design to machine
        learning mathematics.\n\nAfter work, I would often "moonlight" as an independent contractor, helping
        startups prototype their tech ideas and in some cases bring those ideas to production. Now as CTO at Knocki,
        I get to do this every day! I work with a great team of engineers and developers to take wild new ideas off
        the whiteboard and onto the production line."""

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "CTO | Lead Hardware Engineer"
        dates = "Sep 2015 - Present"
        company = "Knocki -- Austin, TX"
        details = """As CTO at a small startup, I have had to wear many hats. My time at Knocki has involved
        everything from PCB design/layout and embedded firmware to manufacturing support and supply chain management.
        Being an \"Internet of Things\" product, Knocki requires development of full cloud platform and mobile app as
        well as mechanical and electrical hardware design. Below is an incomplete list of my responsibilites:
        \n* Work closely with founders to specify full technology stack to meet business needs:\n\t* Electronic sensing
        and networking hardware design\n\t* Embedded system design for algorithmic computation and networking\n\t* Cloud
        software stack\n\t* Mobile app interface specification\n* Design & fabricate prototypes to demonstrate proof
        of concept and feasibility\n* Lead team of engineers to design the product for manufacturability and in-field
        reliability\n* Work with vendors to secure affordable and reliable supply chain for production\n* Work with
        manufacturer to develop production line strategy and assembly/test equipment\n* Embedded firmware
        design:\n\t* Sensor data acquisition\n\t* DSP algorithm design and implementation\n\t* WiFi networking
        interface\n\t* Bare metal C + RTOS"""

        [[params.jobs.list]]
        position = "VLSI Analog Design Engineer"
        dates = "May 2015 - Jul 2016"
        company = "Cirrus Logic -- Austin, TX"
        details = """I worked at Cirrus Logic as an Analog Designer in the MEMS Microphone group. My duties involved
        designing mixed signal VLSI circuitry within the audio processing ASIC inside Cirrus' line of MEMS microphones.
        I worked closely with the following technologies:
        \n* Switched capacitor circuits for mixed-signal filtering\n* Sigma-delta ADCs with high SNR and dynamic
        range\n* Speedpath design for timing closure of PCM data across PVT corners\n* Very low power and low noise
        VLSI design\n* Analog, digital and mixed-signal circuit modeling and simulation"""

        [[params.jobs.list]]
        position = "Product Engineering Intern"
        dates = "May 2013 - Jan 2015"
        company = "Texas Instruments -- Dallas, TX"
        details = """I worked at TI as a product engineering intern for two years during college. While at TI, I worked
        in the Mixed Signal Automotive (MSA) group. My work involved charactarization and debug of audio amplifier ICs,
        primarily class D & AB amplifiers. My duties often required me to develop my own circuitry to fully test the
        capabilities of each amplifier. I became proficient at designing quick prototypes and test jigs for use in the
        lab to test each amplifier. Each prototype had to be high performance and have good build quality, so as not to
        interfere with the measurment results in the lab. Below were some of my responsibilities at this job:
        \n* Validate and characterize class D and AB audio amplifier ICs\n* Design and fabricate test and measurement
        equipment to be used in the lab\n* Fully automate all lab equipment using NI TestStand\n* Assist analog VLSI
        designers in debugging issues found in silicon"""

        [[params.jobs.list]]
        position = "ASIC Design Intern"
        dates = "May 2013 - Aug 2013"
        company = "Emulex -- Austin, TX"
        details = """At Emulex, I worked as an ASIC Design intern in the Network Interface Card (NIC) group. Here I
        designed, simulated and emulated (on FPGAs) RTL to be used in SERDES modules of a 10Gbps ethernet adapter.
        Below are some of the duties I was tasked with:
        \n* Design Verilog RTL for high-speed SERDES (10Gbps)\n* Design SystemVerilog test benches to simulate RTL
        designs\n* Emulate RTL on FPGA systems to ensure timing closure\n* Operate logic analyzers, scopes, and other
        equipment to measure high speed systems"""

    # Projects section
    #[params.projects]
     #   enable = true
      #  icon = "fa-archive"
       # title = "Projects"
        #intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"
#
 #       [[params.projects.list]]
  #      title = "Hugrid"
   #     url = "https://github.com/aerohub/hugrid"
    #    tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"
#
 #       [[params.projects.list]]
  #      title = "Simple FAQ Theme for Hugo"
   #     url = "https://github.com/aerohub/hugo-faq-theme"
    #    tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."
#
 #       [[params.projects.list]]
  #      title = "Hugo Identity"
   #     url = "https://github.com/aerohub/hugo-identity-theme"
    #    tagline = "Little profile/card-style template for Hugo."
#
 #       [[params.projects.list]]
  #      title = "Orbit"
   #     url = "https://github.com/aerohub/hugo-orbit-theme"
    #    tagline = "Hugo Resume/CV Theme for Developers."
#
 #       [[params.projects.list]]
  #      title = "Me"
   #     url = "https://github.com/aerohub/hugo-me-theme"
    #    tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"
                
        [[params.skills.list]]
        skill = "PCB Design"
        level = "98%"

        [[params.skills.list]]
        skill = "Prototyping"
        level = "98%"

        [[params.skills.list]]
        skill = "Solder / Reflow"
        level = "98%"

        [[params.skills.list]]
        skill = "Lab Test & Measurment"
        level = "98%"

        [[params.skills.list]]
        skill = "Embedded Systems"
        level = "95%"
                
        [[params.skills.list]]
        skill = "Mixed Signal VLSI"
        level = "95%"

        [[params.skills.list]]
        skill = "Firmware"
        level = "95%"

        [[params.skills.list]]
        skill = "Matlab / Octave"
        level = "90%"

        [[params.skills.list]]
        skill = "Version Control (git/svn/p4)"
        level = "90%"

        [[params.skills.list]]
        skill = "Scrum / Agile"
        level = "80%"

        [[params.skills.list]]
        skill = "Python"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "John Boyd IV"
