# Page settings
baseurl = "https://phreaknik.github.io/resume/"
languageCode = "en-us"
title = "John Boyd Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"
publishDir = "docs"

[params]

# Meta
    description = "Resume/CV for John Boyd"
    author = "John Boyd"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "John Boyd"
        tagline = "Electrical Engineer"
        avatar = "headshot.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: johnboydiv@gmail.com"
        title = "johnboydiv@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+18177077211"
        title = "+1 (817) 707-7211"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://phreaknik.github.io/fullhack-blog"
        title = "Portfolio Site"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/john-boyd-iv"
        title = "LinkedIn Profile"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/phreaknik"
        title = "GitHub Profile"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc Electrical Engineering\n\nAnalog & Mixed Signal VLSI\n\nGPA: 3.5"
        college = "Texas A&M University"
        dates = "2014 - 2015"

        [[params.education.list]]
        degree = "BSc Electrical Engineering\n\nGPA: 3.34 | Dean's List"
        college = "Texas A&M University"
        dates = "2009 - 2014"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Spanish"
        level = "Conversational"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Hardware Hacking"

        [[params.interests.list]]
        interest = "Rock Climbing"

        [[params.interests.list]]
        interest = "Snowboarding"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """**Summarise your career here**lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, 
        nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat 
        massa quis enim. Donec pede justo. Sed ut perspiciatis unde omnis iste natus error sit voluptatem 
        accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi 
        architecto beatae vitae dicta sunt explicabo."""

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "CTO | Lead Hardware Engineer"
        dates = "July 2016 - Present"
        company = "Knocki -- Austin, TX"
        details = """**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, 
        nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat 
        massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem 
        accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi 
        architecto beatae vitae dicta sunt explicabo."""

        [[params.jobs.list]]
        position = "Independent Contractor"
        dates = "Sep 2015 - July 2016"
        company = "Knocki -- Austin, TX"
        details = """**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, 
        nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat 
        massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem 
        accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi 
        architecto beatae vitae dicta sunt explicabo."""

        [[params.jobs.list]]
        position = "VLSI Analog Design Engineer"
        dates = "May 2015 - July 2016"
        company = "Cirrus Logic -- Austin, TX"
        details = """**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, 
        nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat 
        massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem 
        accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi 
        architecto beatae vitae dicta sunt explicabo."""

        [[params.jobs.list]]
        position = "Product Engineering Intern"
        dates = "May 2013 - Jan 2015"
        company = "Texas Instruments -- Dallas, TX"
        details = """**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, 
        nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat 
        massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem 
        accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi 
        architecto beatae vitae dicta sunt explicabo."""

        [[params.jobs.list]]
        position = "ASIC Design Intern"
        dates = "May 2013 - Aug 2013"
        company = "Emulex -- Austin, TX"
        details = """**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, 
        nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat 
        massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem 
        accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi 
        architecto beatae vitae dicta sunt explicabo."""

    # Projects section
    #[params.projects]
     #   enable = true
      #  icon = "fa-archive"
       # title = "Projects"
        #intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"
#
 #       [[params.projects.list]]
  #      title = "Hugrid"
   #     url = "https://github.com/aerohub/hugrid"
    #    tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"
#
 #       [[params.projects.list]]
  #      title = "Simple FAQ Theme for Hugo"
   #     url = "https://github.com/aerohub/hugo-faq-theme"
    #    tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."
#
 #       [[params.projects.list]]
  #      title = "Hugo Identity"
   #     url = "https://github.com/aerohub/hugo-identity-theme"
    #    tagline = "Little profile/card-style template for Hugo."
#
 #       [[params.projects.list]]
  #      title = "Orbit"
   #     url = "https://github.com/aerohub/hugo-orbit-theme"
    #    tagline = "Hugo Resume/CV Theme for Developers."
#
 #       [[params.projects.list]]
  #      title = "Me"
   #     url = "https://github.com/aerohub/hugo-me-theme"
    #    tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"
                
        [[params.skills.list]]
        skill = "PCB Design"
        level = "98%"

        [[params.skills.list]]
        skill = "Prototyping"
        level = "98%"
                
        [[params.skills.list]]
        skill = "Mixed Signal VLSI"
        level = "95%"

        [[params.skills.list]]
        skill = "Embedded Systems"
        level = "95%"

        [[params.skills.list]]
        skill = "Embedded C"
        level = "95%"

        [[params.skills.list]]
        skill = "Matlab / Octave"
        level = "90%"

        [[params.skills.list]]
        skill = "Scrum / Agile"
        level = "80%"

        [[params.skills.list]]
        skill = "Python"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "John Boyd IV"
